# Dockerfile.multi (Multi-Stage Build)

# === Build ===
FROM node:18-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

# === Exec ===
FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app/build ./build

USER node

EXPOSE 8080

CMD ["node", "build/index.js"]
